accidents = {
        'PEDS': 'Number of forms submitted for persons not in motor vehicle',
        'PERNOTMVIT': 'Number of persons not in motor vehicles in transport (MVIT)',
        'VE_TOTAL': 'Number of Vehicle Forms submitted - ALL',
        'VE_FORMS': 'Number of motor vehicles in transport (MVIT)',
        'PVH_INVL': 'Number of parked/working vehicles involved',
        'PERSONS': 'Number of forms submitted for persons in motor vehicles',
        'PERMVIT': 'Number of persons in motor vehicles in transport (MVIT)',
        'COUNTY': 'County',
        'CITY': 'City',
        'MONTH': 'Month of crash',
        'DAY': 'Day of crash',
        'DAY_WEEK': 'Day of Week',
        'YEAR': 'Year of crash',
        'HOUR': 'Hour of crash',
        'MINUTE': 'Minute of crash',
        'NHS': 'National Highway System',
        'ROAD_FNC': 'Roadway Function Class',
        'ROUTE': 'Route signing',
        'TWAY_ID': 'Trafficway Identifier',
        'TWAY_ID2': 'Trafficway identifier',
        'MILEPT': 'Milepoint',
        'SP_JUR': 'Special Jurisdiction',
        'HARM_EV': 'First harmful event',
        'MAN_COLL': 'Manner of collision',
        'RELJCT1': 'Relation to Junction - Within Interchange Area',
        'RELJCT2': 'Relation to Junction - Specific Location',
        'TYP_INT': 'Type of Intersection',
        'REL_ROAD': 'Relation to Trafficway',
        'WRK_ZONE': 'Work Zone',
        'LGT_COND': 'Light Condition',
        'WEATHER': 'Atmospheric Conditions',
        'WEATHER1': 'Atmospheric Conditions',
        'WEATHER2': 'Atmospheric Conditions',
        'SCH_BUS': 'School Bus Related',
        'RAIL': 'Rail Grade Crossing Identifier',
        'NOT_HOUR': 'Hour of Notification',
        'NOT_MIN': 'Minute of Notification',
        'ARR_HOUR': 'Hour of Arrival at Scene',
        'ARR_MIN': 'Minute of Arrival at Scene',
        'HOSP_HR': 'Hour of EMS Arrival at Hospital',
        'HOSP_MN': 'Minute of EMS Arrival at Hospital',
        'CF1': 'Related Factors - Crash Level',
        'CF2': 'Related Factors - Crash Level',
        'CF3': 'Related Factors - Crash Level',
        'DRUNK_DR': 'Drunk Driver',
        'FATALS': 'Fatalities',
        'VEHICLES': 'Vehicles in Transport (discontinued)',

